[package]
name = "high-storm"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
hex.workspace = true
log.workspace = true
postcard = { workspace = true, features = ["use-std"] }
secp256k1 = { workspace = true, features = ["rand"] }
secp256k1-zkp.workspace = true
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true
sqlx = { workspace = true, features = ["any", "macros", "migrate", "postgres", "sqlite", "runtime-tokio"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url.workspace = true

storm.workspace = true
storm-tree = { path = "../storm-tree" }

[dev-dependencies]
# Used only to replay a Storm Tree inclusion proof step by step in the tests.
monotree.workspace = true
