[service]
port = 9000
external_api_address = "0.0.0.0:9100"

[service.signer]
# Development-only deterministic key. Do not use in production.
private_key = "0101010101010101010101010101010101010101010101010101010101010101"

[service.elements_rpc]
url = "http://elements-1:18884"
username = "high-storm"
password = "high-storm"

[service.db]
url = "postgres:5432"
username = "high-storm"
password = "high-storm"
database = "high-storm-node-1"
max_connections = 5