[package]
name = "storm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "basic"
path = "bin/basic.rs"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
crossterm = "0.28.1"
hex = "0.4.3"
log = "0.4.33"
postcard = { version = "1.1.3", features = ["use-std"] }
ratatui = "0.29.0"
secp256k1-zkp = { version = "0.11.0", features = ["rand-std"] }
serde = { version = "1.0.229", features = ["derive"] }
snow = { version = "0.10.0", features = ["use-p256"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
tracing = "0.1.44"
