[package]
name = "storm"
version.workspace = true
edition.workspace = true

[[bin]]
name = "basic"
path = "bin/basic.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
crossterm.workspace = true
hex.workspace = true
log.workspace = true
postcard = { workspace = true, features = ["use-std"] }
ratatui = { workspace = true, features = ["crossterm_0_28"] }
secp256k1-zkp = { workspace = true, features = ["rand-std"] }
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true
snow = { workspace = true, features = ["use-p256"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
tracing.workspace = true
