[package]
name = "contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
smplx-std = { git = "https://github.com/BlockstreamResearch/smplx", rev = "53087018cd1a8e12c710a44bafc5e32c077edc5a" } # "0.0.10"

[dev-dependencies]
thiserror.workspace = true

storm-tree = { path = "../storm-tree" }

anyhow = "1"
