# DEFAULT CONFIG 

# [build]
# src_dir = "./simf"
# simf_files = ["*.simf"]
# out_dir = "./src/artifacts"

[dependencies]
# TODO: Change to the appropriate tag when it becomes available
std = { git = "https://github.com/BlockstreamResearch/simplicityhl-std.git", rev = "3eafe6bde8c51e88a1f7a76cb297cc4179568bf0" } 

# [regtest]
# mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
# bitcoins = 10_000_000
# rpc_port = 18443
# esplora_port = 3000
# rpc_user = "user"
# rpc_password = "password"

# [test]
# mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
# bitcoins = 10_000_000
# verbosity = 0

# [test.esplora]
# url = "<esplora url>"
# network = "<Liquid, LiquidTestnet, ElementsRegtest>"

# [test.rpc]
# url = "<rpc url>"
# username = "<rpc username>"
# password = "<rpc password>"
